AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  ExampleJavaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.github.frkr.DroolsHandler
      CodeUri: ./target/drools-lambda.jar
      Runtime: java8
