AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  DroolsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'com.github.frkr.DroolsHandler'
      CodeUri: ./target/lambda.jar
      MemorySize: 256
      Timeout: 60
      Runtime: java8
